GET http://localhost:3001/api/bots
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRhbSIsImlhdCI6MTU4NTYwMTYyNCwiZXhwIjoxNTg1NjAxNjU0fQ.Hc9niDNfoI7mXFIYpAx1s1_ybh217P_Tb0XCLr7EYBg

###

POST http://localhost:3001/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRhbSIsImlhdCI6MTU4NjEyMDQ2M30.wMkhJteJuQS0ZKF4QLwICH6JMEvMvBczfwwEfHqOuTQ"
}

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "Adam"
}

###

DELETE http://localhost:3001/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRhbSIsImlhdCI6MTU4NjEyMDU3N30.OCUe5191CgsopAdmJFZb6ZO02vr7R9JDoX6IVucvZWA"
}

